# Generated by Django 5.1.3 on 2024-12-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadato',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
